/-
SPDX-License-Identifier: Apache-2.0
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Formal Frontier Agents
-/
-- Contributors: Prism
module

public import Mathlib.Algebra.Module.RingHom
public import Mathlib.Algebra.Module.Opposite
public import Mathlib.Algebra.Ring.Opposite
public import Mathlib.GroupTheory.FreeAbelianGroup
public import Mathlib.GroupTheory.QuotientGroup.Basic

/-!
# Balanced tensor products over arbitrary rings

This file constructs the balanced tensor product of a right module and a left
module over a possibly noncommutative ring.  Unlike `TensorProduct`, the base
ring is not assumed commutative, and the two scalar actions have their literal
opposite handedness.
-/

@[expose] public section

universe uR uM uN uA

namespace BalancedTensorProduct

variable (R : Type uR) (M : Type uM) (N : Type uN)
variable [Ring R] [AddCommGroup M] [AddCommGroup N]
variable [Module Rᵐᵒᵖ M] [Module R N]

/-- The free additive commutative group used in the quotient construction. -/
abbrev Free := FreeAbelianGroup (M × N)

/-- The elementary relations defining the tensor product of a right module
and a left module over an arbitrary ring. -/
inductive Relation : Free M N → Prop
  | zero_left (n : N) : Relation (FreeAbelianGroup.of (0, n))
  | zero_right (m : M) : Relation (FreeAbelianGroup.of (m, 0))
  | add_left (m₁ m₂ : M) (n : N) :
      Relation (FreeAbelianGroup.of (m₁ + m₂, n) -
        FreeAbelianGroup.of (m₁, n) - FreeAbelianGroup.of (m₂, n))
  | add_right (m : M) (n₁ n₂ : N) :
      Relation (FreeAbelianGroup.of (m, n₁ + n₂) -
        FreeAbelianGroup.of (m, n₁) - FreeAbelianGroup.of (m, n₂))
  | balance (r : R) (m : M) (n : N) :
      Relation (FreeAbelianGroup.of (MulOpposite.op r • m, n) -
        FreeAbelianGroup.of (m, r • n))

/-- The additive subgroup generated by the elementary balanced tensor
relations. -/
def relations : AddSubgroup (Free M N) :=
  AddSubgroup.closure {x | Relation R M N x}

end BalancedTensorProduct

/-- The tensor product of a right `R`-module and a left `R`-module over a
possibly noncommutative ring. -/
abbrev BalancedTensorProduct (R : Type uR) (M : Type uM) (N : Type uN)
    [Ring R] [AddCommGroup M] [AddCommGroup N]
    [Module Rᵐᵒᵖ M] [Module R N] : Type (max uM uN) :=
  BalancedTensorProduct.Free M N ⧸ BalancedTensorProduct.relations R M N

namespace BalancedTensorProduct

variable {R : Type uR} {M : Type uM} {N : Type uN}
variable [Ring R] [AddCommGroup M] [AddCommGroup N]
variable [Module Rᵐᵒᵖ M] [Module R N]

instance : AddCommGroup (BalancedTensorProduct R M N) :=
  inferInstanceAs (AddCommGroup (Free M N ⧸ relations R M N))

/-- The canonical pure tensor. -/
def tmul (m : M) (n : N) : BalancedTensorProduct R M N :=
  QuotientAddGroup.mk' (relations R M N) (FreeAbelianGroup.of (m, n))

@[inherit_doc] scoped notation:100 m:100 " ⊗ᵇ[" R "] " n:101 => tmul (R := R) m n

private theorem relation_eq_zero {x : Free M N} (hx : Relation R M N x) :
    QuotientAddGroup.mk' (relations R M N) x = 0 := by
  change (x : Free M N ⧸ relations R M N) = 0
  exact (QuotientAddGroup.eq_zero_iff x).2 (AddSubgroup.subset_closure hx)

@[simp]
theorem zero_tmul (n : N) : (0 : M) ⊗ᵇ[R] n = 0 :=
  relation_eq_zero (.zero_left n)

@[simp]
theorem tmul_zero (m : M) : m ⊗ᵇ[R] (0 : N) = 0 :=
  relation_eq_zero (.zero_right m)

theorem add_tmul (m₁ m₂ : M) (n : N) :
    (m₁ + m₂) ⊗ᵇ[R] n = m₁ ⊗ᵇ[R] n + m₂ ⊗ᵇ[R] n := by
  have h := relation_eq_zero (R := R) (Relation.add_left (R := R) m₁ m₂ n)
  change QuotientAddGroup.mk' (relations R M N) (FreeAbelianGroup.of (m₁ + m₂, n)) =
    QuotientAddGroup.mk' (relations R M N) (FreeAbelianGroup.of (m₁, n)) +
      QuotientAddGroup.mk' (relations R M N) (FreeAbelianGroup.of (m₂, n))
  rw [← sub_eq_zero, ← sub_sub]
  simpa only [map_sub] using h

theorem tmul_add (m : M) (n₁ n₂ : N) :
    m ⊗ᵇ[R] (n₁ + n₂) = m ⊗ᵇ[R] n₁ + m ⊗ᵇ[R] n₂ := by
  have h := relation_eq_zero (R := R) (Relation.add_right (R := R) m n₁ n₂)
  change QuotientAddGroup.mk' (relations R M N) (FreeAbelianGroup.of (m, n₁ + n₂)) =
    QuotientAddGroup.mk' (relations R M N) (FreeAbelianGroup.of (m, n₁)) +
      QuotientAddGroup.mk' (relations R M N) (FreeAbelianGroup.of (m, n₂))
  rw [← sub_eq_zero, ← sub_sub]
  simpa only [map_sub] using h

theorem smul_tmul (r : R) (m : M) (n : N) :
    (MulOpposite.op r • m) ⊗ᵇ[R] n = m ⊗ᵇ[R] (r • n) := by
  have h := relation_eq_zero (R := R) (Relation.balance r m n)
  change QuotientAddGroup.mk' (relations R M N)
      (FreeAbelianGroup.of (MulOpposite.op r • m, n)) =
    QuotientAddGroup.mk' (relations R M N) (FreeAbelianGroup.of (m, r • n))
  rw [← sub_eq_zero]
  simpa only [map_sub] using h

/-- A biadditive map which is balanced over `R`. -/
structure BalancedMap (A : Type uA) [AddCommGroup A] where
  toFun : M → N → A
  map_zero_left : ∀ n, toFun 0 n = 0
  map_add_left : ∀ m₁ m₂ n, toFun (m₁ + m₂) n = toFun m₁ n + toFun m₂ n
  map_zero_right : ∀ m, toFun m 0 = 0
  map_add_right : ∀ m n₁ n₂, toFun m (n₁ + n₂) = toFun m n₁ + toFun m n₂
  balance : ∀ (r : R) m n, toFun (MulOpposite.op r • m) n = toFun m (r • n)

namespace BalancedMap

variable {A : Type uA} [AddCommGroup A]

instance : CoeFun (BalancedMap (R := R) (M := M) (N := N) A) fun _ => M → N → A :=
  ⟨BalancedMap.toFun⟩

/-- The homomorphism from the free additive group induced by a balanced map.
This is an implementation detail of `BalancedTensorProduct.lift`. -/
def freeLift (b : BalancedMap (R := R) (M := M) (N := N) A) : Free M N →+ A :=
  FreeAbelianGroup.lift fun mn => b mn.1 mn.2

/-- The defining relations lie in the kernel of `BalancedMap.freeLift`.
This is an implementation detail of `BalancedTensorProduct.lift`. -/
theorem relations_le_ker
    (b : BalancedMap (R := R) (M := M) (N := N) A) :
    relations R M N ≤ b.freeLift.ker := by
  rw [relations, AddSubgroup.closure_le]
  intro x hx
  change Relation R M N x at hx
  change b.freeLift x = 0
  rcases hx with (_ | _ | _ | _ | _)
  · simpa [freeLift] using b.map_zero_left _
  · simpa [freeLift] using b.map_zero_right _
  · simp only [freeLift, map_sub, FreeAbelianGroup.lift_apply_of]
    rw [b.map_add_left]
    simp
  · simp only [freeLift, map_sub, FreeAbelianGroup.lift_apply_of]
    rw [b.map_add_right]
    simp
  · simp only [freeLift, map_sub, FreeAbelianGroup.lift_apply_of]
    rw [b.balance, sub_self]

end BalancedMap

/-- Lift a balanced biadditive map to an additive homomorphism from the
balanced tensor product. -/
def lift {A : Type uA} [AddCommGroup A]
    (b : BalancedMap (R := R) (M := M) (N := N) A) :
    BalancedTensorProduct R M N →+ A :=
  QuotientAddGroup.lift (relations R M N) (BalancedMap.freeLift b)
    (BalancedMap.relations_le_ker b)

@[simp]
theorem lift_tmul {A : Type uA} [AddCommGroup A]
    (b : BalancedMap (R := R) (M := M) (N := N) A) (m : M) (n : N) :
    lift b (m ⊗ᵇ[R] n) = b m n := by
  simp [lift, tmul, BalancedMap.freeLift]

/-- Induction on a balanced tensor product by zero, pure tensors, negation,
and addition. -/
@[elab_as_elim]
theorem induction_on {C : BalancedTensorProduct R M N → Prop}
    (x : BalancedTensorProduct R M N) (zero : C 0)
    (pure : ∀ m n, C (m ⊗ᵇ[R] n))
    (neg : ∀ x, C x → C (-x))
    (add : ∀ x y, C x → C y → C (x + y)) : C x := by
  induction x using QuotientAddGroup.induction_on with
  | H x =>
      induction x using FreeAbelianGroup.induction_on' with
      | zero => rw [QuotientAddGroup.mk_zero]; exact zero
      | pure mn => exact pure mn.1 mn.2
      | neg x hx => rw [QuotientAddGroup.mk_neg]; exact neg _ hx
      | add x y hx hy => rw [QuotientAddGroup.mk_add]; exact add _ _ hx hy

/-- Additive maps from a balanced tensor product are determined by their
values on pure tensors. -/
@[ext]
theorem hom_ext {A : Type uA} [AddCommGroup A]
    {g h : BalancedTensorProduct R M N →+ A}
    (H : ∀ m n, g (m ⊗ᵇ[R] n) = h (m ⊗ᵇ[R] n)) : g = h := by
  apply AddMonoidHom.ext
  intro z
  induction z using QuotientAddGroup.induction_on with
  | H z =>
      induction z using FreeAbelianGroup.induction_on' with
      | zero => rw [QuotientAddGroup.mk_zero, map_zero, map_zero]
      | pure mn => exact H mn.1 mn.2
      | neg z hz => rw [QuotientAddGroup.mk_neg, map_neg, map_neg, hz]
      | add x y hx hy => rw [QuotientAddGroup.mk_add, map_add, map_add, hx, hy]

section RightAction

universe uS

variable {S : Type uS} [Ring S] [Module Sᵐᵒᵖ N] [SMulCommClass R Sᵐᵒᵖ N]

/-- The balanced map used to define a compatible right action on the tensor
product. This is an implementation detail of `BalancedTensorProduct.smulAddHom`. -/
def smulBalancedMap (s : Sᵐᵒᵖ) :
    BalancedMap (R := R) (M := M) (N := N) (BalancedTensorProduct R M N) where
  toFun m n := m ⊗ᵇ[R] (s • n)
  map_zero_left n := zero_tmul _
  map_add_left m₁ m₂ n := add_tmul _ _ _
  map_zero_right m := by simp
  map_add_right m n₁ n₂ := by rw [smul_add, tmul_add]
  balance r m n := by rw [smul_tmul, smul_comm]

/-- The action on a balanced tensor product induced by a compatible right
action on the second factor. -/
def smulAddHom (s : Sᵐᵒᵖ) :
    BalancedTensorProduct R M N →+ BalancedTensorProduct R M N :=
  lift (smulBalancedMap (R := R) (M := M) (N := N) s)

instance rightSMul : SMul Sᵐᵒᵖ (BalancedTensorProduct R M N) :=
  ⟨fun s => smulAddHom s⟩

@[simp]
theorem smul_tmul_right (s : Sᵐᵒᵖ) (m : M) (n : N) :
    s • (m ⊗ᵇ[R] n) = m ⊗ᵇ[R] (s • n) :=
  lift_tmul _ _ _

instance rightDistribMulAction : DistribMulAction Sᵐᵒᵖ (BalancedTensorProduct R M N) where
  smul_zero s := (smulAddHom (R := R) (M := M) (N := N) s).map_zero
  smul_add s x y := (smulAddHom (R := R) (M := M) (N := N) s).map_add x y
  one_smul x := by
    exact DFunLike.congr_fun
      (hom_ext (R := R) (M := M) (N := N) (g := smulAddHom (1 : Sᵐᵒᵖ))
        (h := AddMonoidHom.id _) fun m n => by simp [smulAddHom, smulBalancedMap]) x
  mul_smul s t x := by
    exact DFunLike.congr_fun
      (hom_ext (R := R) (M := M) (N := N)
        (g := smulAddHom (s * t))
        (h := (smulAddHom s).comp (smulAddHom t)) fun m n => by
          simp [smulAddHom, smulBalancedMap, mul_smul]) x

instance rightModule : Module Sᵐᵒᵖ (BalancedTensorProduct R M N) where
  zero_smul x := by
    exact DFunLike.congr_fun
      (hom_ext (R := R) (M := M) (N := N) (g := smulAddHom (0 : Sᵐᵒᵖ))
        (h := 0) fun m n => by simp [smulAddHom, smulBalancedMap]) x
  add_smul s t x := by
    exact DFunLike.congr_fun
      (hom_ext (R := R) (M := M) (N := N)
        (g := smulAddHom (s + t))
        (h := smulAddHom s + smulAddHom t) fun m n => by
          simp [smulAddHom, smulBalancedMap, add_smul, tmul_add]) x

end RightAction

end BalancedTensorProduct
