/-
SPDX-License-Identifier: Apache-2.0
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Formal Frontier Agents
-/
-- Contributors: Prism and the worker contributors identified in README.md and Git history
module

public import ProjectiveModules.Module.LocallyConstantRank
public import ProjectiveModules.Module.RankFiberDecomposition
public import Mathlib.CategoryTheory.Skeletal

/-!
# Componentwise-free modules

A module over a commutative ring is componentwise free if, after a finite
complete orthogonal idempotent decomposition of the ring, it is a finite free
module on every component.  The decomposition is only an existential witness:
the predicate does not retain chosen idempotents or bases.

This file develops finite orthogonal refinement and reassembly, proves that
componentwise-free modules are classified by their locally constant stalk-rank
function, compares the explicit model with `ofLocallyConstantRank`, and packages
the result as an equivalence with the skeleton of the corresponding full
subcategory of finite projective modules.
-/

public section

open Function Set
open CategoryTheory

universe u v w

namespace Module

variable {R : Type u} [CommRing R]

/-- The module which is free of rank `n i` on the component cut out by `e i`. -/
abbrev ComponentwiseFreeModel {I : Type*} (e : I → R) (n : I → ℕ) :=
  (i : I) → Fin (n i) → Ideal.span {e i}

/-- A module is componentwise free if it is isomorphic to an explicit model
for some finite complete orthogonal family of idempotents. -/
def ComponentwiseFree (R : Type u) [CommRing R] (M : Type v)
    [AddCommGroup M] [Module R M] : Prop :=
  ∃ c : ℕ, ∃ e : Fin c → R, CompleteOrthogonalIdempotents e ∧
    ∃ n : Fin c → ℕ, Nonempty (M ≃ₗ[R] ComponentwiseFreeModel e n)

/-- A finite orthogonal family whose sum is `e` decomposes the ideal generated
by `e` into the product of the ideals generated by its members. -/
noncomputable def spanFamilyEquiv {I : Type*} [Fintype I]
    (g : I → R) (e : R) (hg : OrthogonalIdempotents g)
    (hsum : ∑ i, g i = e) :
    Ideal.span {e} ≃ₗ[R] (i : I) → Ideal.span {g i} := by
  classical
  let toFun : Ideal.span {e} → (i : I) → Ideal.span {g i} :=
    fun x i ↦ ⟨(x : R) * g i,
      Ideal.mem_span_singleton'.2 ⟨(x : R), rfl⟩⟩
  let invFun : ((i : I) → Ideal.span {g i}) → Ideal.span {e} :=
    fun x ↦ ⟨∑ i, (x i : R), by
      apply Ideal.mem_span_singleton'.2
      refine ⟨∑ i, (x i : R), ?_⟩
      rw [Finset.sum_mul]
      apply Finset.sum_congr rfl
      intro i _
      obtain ⟨r, hr⟩ := Ideal.mem_span_singleton'.1 (x i).property
      rw [← hr, mul_assoc, ← hsum,
        hg.mul_sum_of_mem (Finset.mem_univ i)]⟩
  refine
    { toFun := toFun
      invFun := invFun
      map_add' := by
        intro x y
        funext i
        apply Subtype.ext
        simp [toFun, add_mul]
      map_smul' := by
        intro r x
        funext i
        apply Subtype.ext
        simp [toFun, mul_assoc]
      left_inv := by
        intro x
        apply Subtype.ext
        simp only [invFun, toFun]
        rw [← Finset.mul_sum, hsum]
        obtain ⟨r, hr⟩ := Ideal.mem_span_singleton'.1 x.property
        have he : IsIdempotentElem e := by
          rw [← hsum]
          exact hg.isIdempotentElem_sum
        rw [← hr, mul_assoc, he.eq]
      right_inv := by
        intro x
        funext j
        apply Subtype.ext
        simp only [invFun, toFun, Finset.sum_mul]
        rw [Finset.sum_eq_single j]
        · obtain ⟨r, hr⟩ := Ideal.mem_span_singleton'.1 (x j).property
          rw [← hr, mul_assoc, (hg.idem j).eq]
        · intro i _ hij
          obtain ⟨r, hr⟩ := Ideal.mem_span_singleton'.1 (x i).property
          rw [← hr, mul_assoc, hg.ortho hij, mul_zero]
        · simp }

/-- The explicit component model is finitely generated. -/
theorem componentwiseFreeModel_finite {I : Type*} [Finite I]
    (e : I → R) (n : I → ℕ) :
    Module.Finite R (ComponentwiseFreeModel e n) := by
  let _ : Fintype I := Fintype.ofFinite I
  let _ (i : I) (k : Fin (n i)) : Module.Finite R (Ideal.span {e i}) :=
    Module.Finite.span_singleton R _
  infer_instance

/-- The explicit component model is projective when its component generators
are idempotent. -/
theorem componentwiseFreeModel_projective {I : Type*} [Finite I]
    (e : I → R) (n : I → ℕ) (he : ∀ i, IsIdempotentElem (e i)) :
    Module.Projective R (ComponentwiseFreeModel e n) := by
  let _ : Fintype I := Fintype.ofFinite I
  let _ (i : I) (k : Fin (n i)) : Module.Projective R (Ideal.span {e i}) :=
    (he i).projective_span
  let _ (i : I) : Module.Projective R (Fin (n i) → Ideal.span {e i}) :=
    Module.Projective.of_equiv'
      (DirectSum.linearEquivFunOnFintype R (Fin (n i)) fun _ ↦ Ideal.span {e i})
  exact Module.Projective.of_equiv'
    (DirectSum.linearEquivFunOnFintype R I fun i ↦
      (k : Fin (n i)) → Ideal.span {e i})

/-- Componentwise freeness is invariant under linear equivalence. -/
theorem ComponentwiseFree.equiv {M : Type v} {N : Type w}
    [AddCommGroup M] [Module R M] [AddCommGroup N] [Module R N]
    (hM : ComponentwiseFree R M) (E : N ≃ₗ[R] M) :
    ComponentwiseFree R N := by
  rcases hM with ⟨c, e, he, n, ⟨h⟩⟩
  exact ⟨c, e, he, n, ⟨E.trans h⟩⟩

/-- An explicit model indexed by any finite type gives componentwise freeness;
the witness is reindexed by a finite ordinal only to match the predicate's
small, concrete existential interface. -/
theorem componentwiseFree_of_model {I : Type*} [Fintype I]
    {M : Type v} [AddCommGroup M] [Module R M]
    (e : I → R) (n : I → ℕ) (he : CompleteOrthogonalIdempotents e)
    (E : Nonempty (M ≃ₗ[R] ComponentwiseFreeModel e n)) :
    ComponentwiseFree R M := by
  classical
  let q : Fin (Fintype.card I) ≃ I := (Fintype.equivFin I).symm
  refine ⟨Fintype.card I, e ∘ q,
    (CompleteOrthogonalIdempotents.equiv q).2 he, n ∘ q, ?_⟩
  exact E.map fun h ↦ h.trans
    (LinearEquiv.piCongrLeft R
      (fun i : I ↦ Fin (n i) → Ideal.span {e i}) q).symm

/-- A componentwise-free module is finitely generated. -/
theorem ComponentwiseFree.finite {M : Type v} [AddCommGroup M] [Module R M]
    (hM : ComponentwiseFree R M) : Module.Finite R M := by
  rcases hM with ⟨c, e, he, n, ⟨h⟩⟩
  let _ : Module.Finite R (ComponentwiseFreeModel e n) :=
    componentwiseFreeModel_finite e n
  exact Module.Finite.equiv h.symm

/-- A componentwise-free module is projective. -/
theorem ComponentwiseFree.projective {M : Type v} [AddCommGroup M] [Module R M]
    (hM : ComponentwiseFree R M) : Module.Projective R M := by
  rcases hM with ⟨c, e, he, n, ⟨h⟩⟩
  let _ : Module.Projective R (ComponentwiseFreeModel e n) :=
    componentwiseFreeModel_projective e n he.idem
  exact Module.Projective.of_equiv' h.symm

/-- At a prime avoiding a member of a complete orthogonal family, the explicit
component model has the displayed rank of that member. -/
theorem rankAtStalk_componentwiseFreeModel_of_notMem {I : Type*} [Fintype I]
    (e : I → R) (n : I → ℕ) (he : CompleteOrthogonalIdempotents e)
    (i : I) (p : PrimeSpectrum R) (hi : e i ∉ p.asIdeal) :
    rankAtStalk (R := R) (ComponentwiseFreeModel e n) p = n i := by
  classical
  let _ (j : I) (k : Fin (n j)) : Module.Finite R (Ideal.span {e j}) :=
    Module.Finite.span_singleton R _
  let _ (j : I) (k : Fin (n j)) : Module.Projective R (Ideal.span {e j}) :=
    (he.idem j).projective_span
  let _ (j : I) : Module.Projective R (Fin (n j) → Ideal.span {e j}) :=
    Module.Projective.of_equiv'
      (DirectSum.linearEquivFunOnFintype R (Fin (n j)) fun _ ↦ Ideal.span {e j})
  rw [rankAtStalk_pi, finsum_eq_sum_of_fintype]
  calc
    (∑ j : I, rankAtStalk (R := R) (Fin (n j) → Ideal.span {e j}) p) =
        ∑ j : I, if j = i then n i else 0 := by
      apply Finset.sum_congr rfl
      intro j _
      rw [rankAtStalk_pi, finsum_eq_sum_of_fintype]
      by_cases hji : j = i
      · subst j
        simp only [↓reduceIte]
        calc
          (∑ k : Fin (n i), rankAtStalk (R := R) (Ideal.span {e i}) p) =
              ∑ _k : Fin (n i), 1 :=
            Finset.sum_congr rfl fun _ _ ↦
              (he.idem i).rankAtStalk_span_eq_one p hi
          _ = n i := by simp
      · simp only [hji, ↓reduceIte]
        have hj : e j ∈ p.asIdeal := by
          by_contra hj
          have hzero : e j * e i ∈ p.asIdeal := by
            rw [he.ortho hji]
            exact p.asIdeal.zero_mem
          exact hi ((inferInstance : p.asIdeal.IsPrime).mem_or_mem hzero |>.resolve_left hj)
        apply Finset.sum_eq_zero
        intro k _
        exact (he.idem j).rankAtStalk_span_eq_zero p hj
    _ = n i := by
      simp only [Finset.sum_ite_eq', Finset.mem_univ, ↓reduceIte]

/-- The numerical rank prescribed by an explicit component model at a prime. -/
noncomputable def componentwiseFreeModelRank {I : Type*} [Fintype I]
    (e : I → R) (n : I → ℕ) (p : PrimeSpectrum R) : ℕ := by
  classical
  exact ∑ i, if e i ∈ p.asIdeal then 0 else n i

/-- The exact stalk-rank formula for an explicit component model. -/
theorem rankAtStalk_componentwiseFreeModel {I : Type*} [Fintype I]
    (e : I → R) (n : I → ℕ) (he : CompleteOrthogonalIdempotents e)
    (p : PrimeSpectrum R) :
    rankAtStalk (R := R) (ComponentwiseFreeModel e n) p =
      componentwiseFreeModelRank e n p := by
  classical
  obtain ⟨i, hi⟩ : ∃ i, e i ∉ p.asIdeal := by
    by_contra h
    simp only [not_exists, not_not] at h
    have hsum : ∑ i, e i ∈ p.asIdeal := p.asIdeal.sum_mem fun i _ ↦ h i
    rw [he.complete] at hsum
    exact p.asIdeal.one_notMem hsum
  rw [rankAtStalk_componentwiseFreeModel_of_notMem e n he i p hi]
  unfold componentwiseFreeModelRank
  rw [Finset.sum_eq_single i]
  · simp only [hi, ↓reduceIte]
  · intro j _ hji
    have hj : e j ∈ p.asIdeal := by
      by_contra hj
      have hzero : e j * e i ∈ p.asIdeal := by
        rw [he.ortho hji]
        exact p.asIdeal.zero_mem
      exact hi ((inferInstance : p.asIdeal.IsPrime).mem_or_mem hzero |>.resolve_left hj)
    simp only [hj, ↓reduceIte]
  · simp

/-- Multiplying a finite orthogonal family by an idempotent preserves
orthogonality. -/
theorem orthogonalIdempotents_mul_right {I : Type*} {e : I → R} {d : R}
    (he : OrthogonalIdempotents e) (hd : IsIdempotentElem d) :
    OrthogonalIdempotents fun i ↦ e i * d := by
  constructor
  · intro i
    rw [IsIdempotentElem]
    calc
      e i * d * (e i * d) = (e i * e i) * (d * d) := by ac_rfl
      _ = e i * d := by rw [(he.idem i).eq, hd.eq]
  · intro i j hij
    calc
      e i * d * (e j * d) = (e i * e j) * (d * d) := by ac_rfl
      _ = 0 := by rw [he.ortho hij, zero_mul]

/-- Multiplying an orthogonal family on the left by an idempotent also
preserves orthogonality. -/
theorem orthogonalIdempotents_mul_left {I : Type*} {e : I → R} {d : R}
    (he : OrthogonalIdempotents e) (hd : IsIdempotentElem d) :
    OrthogonalIdempotents fun i ↦ d * e i := by
  simpa only [mul_comm] using orthogonalIdempotents_mul_right he hd

/-- Refining the components `e i` by a second complete orthogonal family
`d j` does not change the explicit model. -/
noncomputable def componentwiseFreeModelRefineRightEquiv
    {I J : Type*} [Fintype I] [Fintype J]
    (e : I → R) (n : I → ℕ) (d : J → R)
    (he : CompleteOrthogonalIdempotents e)
    (hd : CompleteOrthogonalIdempotents d) :
    ComponentwiseFreeModel e n ≃ₗ[R]
      (i : I) → Fin (n i) → (j : J) → Ideal.span {e i * d j} :=
  LinearEquiv.piCongrRight fun i ↦ LinearEquiv.piCongrRight fun _ ↦
    spanFamilyEquiv (fun j ↦ e i * d j) (e i)
      (orthogonalIdempotents_mul_left hd.toOrthogonalIdempotents (he.idem i)) (by
        rw [← Finset.mul_sum, hd.complete, mul_one])

/-- Reassembly in the other order: the family `e i * d j` also refines
`d j`. -/
noncomputable def componentwiseFreeModelRefineLeftEquiv
    {I J : Type*} [Fintype I] [Fintype J]
    (e : I → R) (d : J → R) (m : J → ℕ)
    (he : CompleteOrthogonalIdempotents e)
    (hd : CompleteOrthogonalIdempotents d) :
    ComponentwiseFreeModel d m ≃ₗ[R]
      (j : J) → Fin (m j) → (i : I) → Ideal.span {e i * d j} :=
  LinearEquiv.piCongrRight fun j ↦ LinearEquiv.piCongrRight fun _ ↦
    spanFamilyEquiv (fun i ↦ e i * d j) (d j)
      (orthogonalIdempotents_mul_right he.toOrthogonalIdempotents (hd.idem j)) (by
        rw [← Finset.sum_mul, he.complete, one_mul])

/-- On a nonzero common idempotent corner, equal stalk ranks identify the
two displayed finite ranks; on the zero corner both blocks are zero. -/
noncomputable def componentBlockEquiv {I J : Type*} [Fintype I] [Fintype J]
    (e : I → R) (n : I → ℕ) (d : J → R) (m : J → ℕ)
    (hrank : ∀ i j, e i * d j ≠ 0 → n i = m j) (i : I) (j : J) :
    (Fin (n i) → Ideal.span {e i * d j}) ≃ₗ[R]
      (Fin (m j) → Ideal.span {e i * d j}) := by
  classical
  by_cases hzero : e i * d j = 0
  · haveI : Subsingleton (Ideal.span {e i * d j}) := by
      rw [Ideal.span_singleton_eq_bot.mpr hzero]
      infer_instance
    exact LinearEquiv.ofSubsingleton _ _
  · exact LinearEquiv.piCongrLeft R
      (fun _ : Fin (m j) ↦ Ideal.span {e i * d j})
      (finCongr (hrank i j hzero))

/-- Compare the two orderings of a common orthogonal refinement. -/
noncomputable def componentRefinementComparisonEquiv
    {I J : Type*} [Fintype I] [Fintype J]
    (e : I → R) (n : I → ℕ) (d : J → R) (m : J → ℕ)
    (hrank : ∀ i j, e i * d j ≠ 0 → n i = m j) :
    ((i : I) → Fin (n i) → (j : J) → Ideal.span {e i * d j}) ≃ₗ[R]
      ((j : J) → Fin (m j) → (i : I) → Ideal.span {e i * d j}) where
  toFun x j l i := componentBlockEquiv e n d m hrank i j (fun k ↦ x i k j) l
  invFun y i k j :=
    (componentBlockEquiv e n d m hrank i j).symm (fun l ↦ y j l i) k
  left_inv x := by
    funext i k j
    exact congrFun ((componentBlockEquiv e n d m hrank i j).symm_apply_apply
      (fun k ↦ x i k j)) k
  right_inv y := by
    funext j l i
    exact congrFun ((componentBlockEquiv e n d m hrank i j).apply_symm_apply
      (fun l ↦ y j l i)) l
  map_add' x y := by
    funext j l i
    exact congrFun ((componentBlockEquiv e n d m hrank i j).map_add
      (fun k ↦ x i k j) (fun k ↦ y i k j)) l
  map_smul' r x := by
    funext j l i
    exact congrFun ((componentBlockEquiv e n d m hrank i j).map_smul r
      (fun k ↦ x i k j)) l

/-- Explicit component models with equal stalk-rank functions are linearly
equivalent.  The proof refines both decompositions by the products `e i * d j`
and handles zero corners separately. -/
noncomputable def componentwiseFreeModelEquivOfRankAtStalkEq
    {I J : Type*} [Fintype I] [Fintype J]
    (e : I → R) (n : I → ℕ) (he : CompleteOrthogonalIdempotents e)
    (d : J → R) (m : J → ℕ) (hd : CompleteOrthogonalIdempotents d)
    (hrank : rankAtStalk (R := R) (ComponentwiseFreeModel e n) =
      rankAtStalk (ComponentwiseFreeModel d m)) :
    ComponentwiseFreeModel e n ≃ₗ[R] ComponentwiseFreeModel d m := by
  classical
  let hcorner : ∀ i j, e i * d j ≠ 0 → n i = m j := by
    intro i j hne
    have hidem : IsIdempotentElem (e i * d j) := by
      rw [IsIdempotentElem]
      calc
        e i * d j * (e i * d j) = (e i * e i) * (d j * d j) := by ac_rfl
        _ = e i * d j := by rw [(he.idem i).eq, (hd.idem j).eq]
    obtain ⟨p, hp, -, hnot⟩ :=
      Ideal.exists_le_prime_notMem_of_isIdempotentElem (⊥ : Ideal R)
        (e i * d j) hidem (by simpa using hne)
    let q : PrimeSpectrum R := ⟨p, hp⟩
    have hei : e i ∉ q.asIdeal := by
      intro h
      exact hnot (q.asIdeal.mul_mem_right (d j) h)
    have hdj : d j ∉ q.asIdeal := by
      intro h
      exact hnot (q.asIdeal.mul_mem_left (e i) h)
    calc
      n i = rankAtStalk (R := R) (ComponentwiseFreeModel e n) q :=
        (rankAtStalk_componentwiseFreeModel_of_notMem e n he i q hei).symm
      _ = rankAtStalk (R := R) (ComponentwiseFreeModel d m) q := congrFun hrank q
      _ = m j := rankAtStalk_componentwiseFreeModel_of_notMem d m hd j q hdj
  exact (componentwiseFreeModelRefineRightEquiv e n d he hd).trans
    ((componentRefinementComparisonEquiv e n d m hcorner).trans
      (componentwiseFreeModelRefineLeftEquiv e d m he hd).symm)

section CanonicalRealization

/-- The nonempty rank fibers of a prescribed locally constant rank, using its
canonical threshold-ideal realization. -/
abbrev locallyConstantRankFiberIndex
    (f : LocallyConstant (PrimeSpectrum R) ℕ) :=
  rankFiberIndex R (ModuleCat.FiniteProjective.ofLocallyConstantRank R f)

/-- The idempotent cutting out a nonempty rank fiber of the canonical
realization of `f`. -/
noncomputable abbrev locallyConstantRankFiberIdempotent
    (f : LocallyConstant (PrimeSpectrum R) ℕ)
    (j : locallyConstantRankFiberIndex f) : R :=
  rankFiberIdempotent R (ModuleCat.FiniteProjective.ofLocallyConstantRank R f) j

/-- The value of the rank on a nonempty rank fiber of the canonical
realization of `f`. -/
noncomputable abbrev locallyConstantRankFiberRank
    (f : LocallyConstant (PrimeSpectrum R) ℕ)
    (j : locallyConstantRankFiberIndex f) : ℕ :=
  rankFiberRank R (ModuleCat.FiniteProjective.ofLocallyConstantRank R f) j

/-- The value on a rank fiber is bounded by the global bound used in the
threshold construction. -/
theorem locallyConstantRankFiberRank_le_rankBound
    (f : LocallyConstant (PrimeSpectrum R) ℕ)
    (j : locallyConstantRankFiberIndex f) :
    locallyConstantRankFiberRank f j ≤
      ModuleCat.FiniteProjective.rankBound f := by
  let p := Function.Fiber.preimage
    (rankLocallyConstant R (ModuleCat.FiniteProjective.ofLocallyConstantRank R f)) j
  calc
    locallyConstantRankFiberRank f j =
        rankAtStalk (R := R)
          (ModuleCat.FiniteProjective.ofLocallyConstantRank R f) p :=
      (rankAtStalk_eq_rankFiberRank_of_mem R
        (ModuleCat.FiniteProjective.ofLocallyConstantRank R f) j p
        ((Function.Fiber.mem_iff_eq_image
          (rankLocallyConstant R
            (ModuleCat.FiniteProjective.ofLocallyConstantRank R f)) p j).2
          (Function.Fiber.map_preimage_eq_image
            (rankLocallyConstant R
              (ModuleCat.FiniteProjective.ofLocallyConstantRank R f)) j))).symm
    _ = f p := congrFun
      (ModuleCat.FiniteProjective.rankAtStalk_ofLocallyConstantRank f) p
    _ ≤ ModuleCat.FiniteProjective.rankBound f :=
      ModuleCat.FiniteProjective.le_rankBound f p

/-- On a rank fiber, a threshold idempotent is either one or zero.  This is
the key finite orthogonal comparison behind the explicit component model. -/
theorem rankIdempotent_mul_locallyConstantRankFiberIdempotent
    (f : LocallyConstant (PrimeSpectrum R) ℕ)
    (i : Fin (ModuleCat.FiniteProjective.rankBound f))
    (j : locallyConstantRankFiberIndex f) :
    ModuleCat.FiniteProjective.rankIdempotent f i *
        locallyConstantRankFiberIdempotent f j =
      if i.1 < locallyConstantRankFiberRank f j then
        locallyConstantRankFiberIdempotent f j else 0 := by
  classical
  split_ifs with hij
  · apply PrimeSpectrum.basicOpen_injOn_isIdempotentElem
      ((ModuleCat.FiniteProjective.rankIdempotent_isIdempotent f i).mul
        (rankFiberIdempotent_isIdempotent R
          (ModuleCat.FiniteProjective.ofLocallyConstantRank R f) j))
      (rankFiberIdempotent_isIdempotent R
        (ModuleCat.FiniteProjective.ofLocallyConstantRank R f) j)
    rw [PrimeSpectrum.basicOpen_mul]
    apply le_antisymm inf_le_right
    intro p hp
    refine ⟨?_, hp⟩
    have hpj : p ∈ j.1 :=
      (rankFiberIdempotent_notMem_iff R
        (ModuleCat.FiniteProjective.ofLocallyConstantRank R f) j p).1 hp
    have hrank : f p = locallyConstantRankFiberRank f j := by
      rw [← congrFun
        (ModuleCat.FiniteProjective.rankAtStalk_ofLocallyConstantRank f) p]
      exact rankAtStalk_eq_rankFiberRank_of_mem R
        (ModuleCat.FiniteProjective.ofLocallyConstantRank R f) j p hpj
    exact (ModuleCat.FiniteProjective.rankIdempotent_notMem_iff f i p).2
      (hrank.symm ▸ hij)
  · apply PrimeSpectrum.basicOpen_injOn_isIdempotentElem
      ((ModuleCat.FiniteProjective.rankIdempotent_isIdempotent f i).mul
        (rankFiberIdempotent_isIdempotent R
          (ModuleCat.FiniteProjective.ofLocallyConstantRank R f) j))
      IsIdempotentElem.zero
    rw [PrimeSpectrum.basicOpen_mul, PrimeSpectrum.basicOpen_zero]
    apply bot_unique
    intro p hp
    have hpj : p ∈ j.1 :=
      (rankFiberIdempotent_notMem_iff R
        (ModuleCat.FiniteProjective.ofLocallyConstantRank R f) j p).1 hp.2
    have hrank : f p = locallyConstantRankFiberRank f j := by
      rw [← congrFun
        (ModuleCat.FiniteProjective.rankAtStalk_ofLocallyConstantRank f) p]
      exact rankAtStalk_eq_rankFiberRank_of_mem R
        (ModuleCat.FiniteProjective.ofLocallyConstantRank R f) j p hpj
    exact hij ((ModuleCat.FiniteProjective.rankIdempotent_notMem_iff f i p).1 hp.1
      |>.trans_eq hrank)

/-- The threshold idempotent is the sum of the rank-fiber idempotents on
which its threshold is active. -/
theorem rankIdempotent_eq_sum_locallyConstantRankFiberIdempotent
    (f : LocallyConstant (PrimeSpectrum R) ℕ)
    (i : Fin (ModuleCat.FiniteProjective.rankBound f)) :
    ModuleCat.FiniteProjective.rankIdempotent f i =
      ∑ j : locallyConstantRankFiberIndex f,
        if i.1 < locallyConstantRankFiberRank f j then
          locallyConstantRankFiberIdempotent f j else 0 := by
  classical
  calc
    ModuleCat.FiniteProjective.rankIdempotent f i =
        ModuleCat.FiniteProjective.rankIdempotent f i * 1 := by rw [mul_one]
    _ = ModuleCat.FiniteProjective.rankIdempotent f i *
        (∑ j : locallyConstantRankFiberIndex f,
          locallyConstantRankFiberIdempotent f j) := by
      rw [rankFiberIdempotents_complete R
        (ModuleCat.FiniteProjective.ofLocallyConstantRank R f) |>.complete]
    _ = ∑ j : locallyConstantRankFiberIndex f,
        ModuleCat.FiniteProjective.rankIdempotent f i *
          locallyConstantRankFiberIdempotent f j := by rw [Finset.mul_sum]
    _ = _ := Finset.sum_congr rfl fun j _ ↦
      rankIdempotent_mul_locallyConstantRankFiberIdempotent f i j

/-- The threshold-ideal realization is linearly equivalent to its explicit
complete-orthogonal-idempotent component model. -/
noncomputable def rankModuleEquivComponentwiseFreeModel
    (f : LocallyConstant (PrimeSpectrum R) ℕ) :
    ModuleCat.FiniteProjective.rankModule R f ≃ₗ[R]
      ComponentwiseFreeModel
        (locallyConstantRankFiberIdempotent f)
        (locallyConstantRankFiberRank f) := by
  classical
  let b := ModuleCat.FiniteProjective.rankBound f
  let d := locallyConstantRankFiberIdempotent f
  let n := locallyConstantRankFiberRank f
  let toFun : ModuleCat.FiniteProjective.rankModule R f →
      ComponentwiseFreeModel d n := fun x j k ↦
    ⟨(x ⟨k.1, lt_of_lt_of_le k.2
      (locallyConstantRankFiberRank_le_rankBound f j)⟩ : R) * d j,
      Ideal.mem_span_singleton'.2 ⟨_, rfl⟩⟩
  let invFun : ComponentwiseFreeModel d n →
      ModuleCat.FiniteProjective.rankModule R f := fun y i ↦
    ⟨∑ j, if h : i.1 < n j then (y j ⟨i.1, h⟩ : R) else 0, by
      apply Ideal.sum_mem _
      intro j _
      split_ifs with h
      · obtain ⟨r, hr⟩ := Ideal.mem_span_singleton'.1 (y j ⟨i.1, h⟩).property
        apply Ideal.mem_span_singleton'.2
        refine ⟨(y j ⟨i.1, h⟩ : R), ?_⟩
        rw [← hr, mul_assoc, mul_comm (d j),
          rankIdempotent_mul_locallyConstantRankFiberIdempotent f i j]
        simp only [n, d, h, ↓reduceIte]
      · exact Ideal.zero_mem _⟩
  refine
    { toFun := toFun
      invFun := invFun
      map_add' := by
        intro x y
        funext j k
        apply Subtype.ext
        simp [toFun, add_mul]
      map_smul' := by
        intro r x
        funext j k
        apply Subtype.ext
        simp [toFun, mul_assoc]
      left_inv := by
        intro x
        funext i
        apply Subtype.ext
        simp only [invFun, toFun]
        calc
          (∑ j, if h : i.1 < n j then
              (x ⟨i.1, lt_of_lt_of_le h
                (locallyConstantRankFiberRank_le_rankBound f j)⟩ : R) * d j else 0) =
              ∑ j, if h : i.1 < n j then (x i : R) * d j else 0 := by
            apply Finset.sum_congr rfl
            intro j _
            split_ifs with h
            · rw [show (⟨i.1, lt_of_lt_of_le h
                  (locallyConstantRankFiberRank_le_rankBound f j)⟩ : Fin b) = i from
                Fin.ext rfl]
            · rfl
          _ = (x i : R) * ∑ j, if i.1 < n j then d j else 0 := by
            rw [Finset.mul_sum]
            apply Finset.sum_congr rfl
            intro j _
            split_ifs <;> simp only [mul_zero]
          _ = (x i : R) * ModuleCat.FiniteProjective.rankIdempotent f i := by
            rw [← rankIdempotent_eq_sum_locallyConstantRankFiberIdempotent f i]
          _ = (x i : R) := by
            obtain ⟨r, hr⟩ := Ideal.mem_span_singleton'.1 (x i).property
            rw [← hr, mul_assoc,
              (ModuleCat.FiniteProjective.rankIdempotent_isIdempotent f i).eq]
      right_inv := by
        intro y
        funext j k
        apply Subtype.ext
        simp only [toFun, invFun, Finset.sum_mul]
        rw [Finset.sum_eq_single j]
        · simp only [k.2, ↓reduceDIte]
          obtain ⟨r, hr⟩ := Ideal.mem_span_singleton'.1 (y j k).property
          rw [← hr, mul_assoc,
            (rankFiberIdempotent_isIdempotent R
              (ModuleCat.FiniteProjective.ofLocallyConstantRank R f) j).eq]
        · intro l _ hlj
          split_ifs with h
          · obtain ⟨r, hr⟩ := Ideal.mem_span_singleton'.1 (y l ⟨k.1, h⟩).property
            rw [← hr, mul_assoc,
              (rankFiberIdempotents_complete R
                (ModuleCat.FiniteProjective.ofLocallyConstantRank R f)).ortho hlj,
              mul_zero]
          · rw [zero_mul]
        · simp }

/-- The accepted canonical realization of any locally constant rank is
componentwise free in the explicit complete-orthogonal-idempotent sense. -/
theorem componentwiseFree_ofLocallyConstantRank
    (f : LocallyConstant (PrimeSpectrum R) ℕ) :
    ComponentwiseFree R
      (ModuleCat.FiniteProjective.ofLocallyConstantRank R f) :=
  componentwiseFree_of_model
    (locallyConstantRankFiberIdempotent f)
    (locallyConstantRankFiberRank f)
    (rankFiberIdempotents_complete R
      (ModuleCat.FiniteProjective.ofLocallyConstantRank R f))
    ⟨rankModuleEquivComponentwiseFreeModel f⟩

end CanonicalRealization

/-- Componentwise-free modules in independent universes with the same stalk
rank are nonemptily linearly equivalent. -/
theorem ComponentwiseFree.nonempty_linearEquiv_of_rankAtStalk_eq
    {M : Type v} {N : Type w}
    [AddCommGroup M] [Module R M] [AddCommGroup N] [Module R N]
    (hM : ComponentwiseFree R M) (hN : ComponentwiseFree R N)
    (hrank : rankAtStalk (R := R) M = rankAtStalk (R := R) N) :
    Nonempty (M ≃ₗ[R] N) := by
  rcases hM with ⟨c, e, he, n, ⟨EM⟩⟩
  rcases hN with ⟨k, d, hd, m, ⟨EN⟩⟩
  exact ⟨EM.trans ((componentwiseFreeModelEquivOfRankAtStalkEq e n he d m hd
    ((rankAtStalk_eq_of_equiv EM).symm.trans
      (hrank.trans (rankAtStalk_eq_of_equiv EN)))).trans EN.symm)⟩

/-- A finite projective module is componentwise free exactly when it is
linearly equivalent to the canonical realization of its stalk-rank function. -/
theorem ComponentwiseFree.iff_nonempty_linearEquiv_ofLocallyConstantRank
    {M : Type v} [AddCommGroup M] [Module R M]
    [Module.Finite R M] [Module.Projective R M] :
    ComponentwiseFree R M ↔
      Nonempty (M ≃ₗ[R] ModuleCat.FiniteProjective.ofLocallyConstantRank R
        (rankLocallyConstant R M)) := by
  constructor
  · intro hM
    apply hM.nonempty_linearEquiv_of_rankAtStalk_eq
      (componentwiseFree_ofLocallyConstantRank (R := R) (rankLocallyConstant R M))
    ext p
    rw [ModuleCat.FiniteProjective.rankAtStalk_ofLocallyConstantRank]
    exact (rankLocallyConstant_apply R M p).symm
  · rintro ⟨E⟩
    exact (componentwiseFree_ofLocallyConstantRank (R := R)
      (rankLocallyConstant R M)).equiv E

end Module

namespace ModuleCat

variable (R : Type u) [CommRing R]

/-- The object property of a finite projective module being componentwise
free. -/
def isComponentwiseFree :
    ObjectProperty (FiniteProjective.{u, u} R) :=
  fun M ↦ Module.ComponentwiseFree R M

/-- The full subcategory of finite projective modules which admit an explicit
finite complete-orthogonal-idempotent component model. -/
abbrev ComponentwiseFreeFiniteProjective :=
  (isComponentwiseFree R).FullSubcategory

namespace ComponentwiseFreeFiniteProjective

variable {R}

/-- An isomorphism in the componentwise-free full subcategory induces the
underlying linear equivalence. -/
noncomputable def isoToLinearEquiv
    {X Y : ComponentwiseFreeFiniteProjective R} (e : X ≅ Y) :
    X.obj ≃ₗ[R] Y.obj :=
  ((ObjectProperty.ι (isFiniteProjective R)).mapIso
    ((ObjectProperty.ι (isComponentwiseFree R)).mapIso e)).toLinearEquiv

/-- A linear equivalence between the underlying modules lifts to an
isomorphism in the componentwise-free full subcategory. -/
noncomputable def isoOfLinearEquiv
    {X Y : ComponentwiseFreeFiniteProjective R} (e : X.obj ≃ₗ[R] Y.obj) :
    X ≅ Y :=
  InducedCategory.isoMk (InducedCategory.isoMk e.toModuleIso)

end ComponentwiseFreeFiniteProjective

/-- The locally constant stalk-rank function represented by an object of the
skeleton of componentwise-free finite projectives. -/
noncomputable def componentwiseFreeSkeletonRank :
    Skeleton (ComponentwiseFreeFiniteProjective R) →
      LocallyConstant (PrimeSpectrum R) ℕ :=
  fun X ↦ Module.rankLocallyConstant R
    ((fromSkeleton (ComponentwiseFreeFiniteProjective R)).obj X).obj

/-- The skeleton of componentwise-free finite projective modules is
classified by locally constant natural-valued rank functions. -/
noncomputable def componentwiseFreeSkeletonEquiv :
    Skeleton (ComponentwiseFreeFiniteProjective R) ≃
      LocallyConstant (PrimeSpectrum R) ℕ := by
  apply Equiv.ofBijective (componentwiseFreeSkeletonRank R)
  constructor
  · intro X Y hXY
    rw [← toSkeleton_fromSkeleton_obj X, ← toSkeleton_fromSkeleton_obj Y]
    apply congr_toSkeleton_of_iso
    apply ComponentwiseFreeFiniteProjective.isoOfLinearEquiv
    exact Nonempty.some <|
      Module.ComponentwiseFree.nonempty_linearEquiv_of_rankAtStalk_eq
        ((fromSkeleton (ComponentwiseFreeFiniteProjective R)).obj X).property
        ((fromSkeleton (ComponentwiseFreeFiniteProjective R)).obj Y).property
        (by
          ext p
          exact congrFun (congrArg LocallyConstant.toFun hXY) p)
  · intro f
    let P : FiniteProjective R := FiniteProjective.ofLocallyConstantRank R f
    let X : ComponentwiseFreeFiniteProjective R :=
      ⟨P, Module.componentwiseFree_ofLocallyConstantRank f⟩
    refine ⟨toSkeleton X, ?_⟩
    let E := ComponentwiseFreeFiniteProjective.isoToLinearEquiv
      (fromSkeletonToSkeletonIso X)
    ext p
    calc
      componentwiseFreeSkeletonRank R (toSkeleton X) p =
          Module.rankAtStalk (R := R)
            ((fromSkeleton (ComponentwiseFreeFiniteProjective R)).obj
              (toSkeleton X)).obj p :=
        Module.rankLocallyConstant_apply R _ p
      _ = Module.rankAtStalk (R := R) X.obj p :=
        congrFun (Module.rankAtStalk_eq_of_equiv E) p
      _ = f p := congrFun
        (FiniteProjective.rankAtStalk_ofLocallyConstantRank f) p

end ModuleCat
