/-
SPDX-License-Identifier: Apache-2.0
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Formal Frontier Agents
-/
-- Contributors: Formal Frontier Agents, including Prism; see docs/CREDITS.md
module

public import ProjectiveModules.Category.FiniteProjective
public import Mathlib.LinearAlgebra.DirectSum.Finite
public import Mathlib.RingTheory.Spectrum.Prime.FreeLocus

/-!
# Realizing locally constant stalk-rank functions

This file constructs a finite projective module with any prescribed locally
constant natural-valued function on `PrimeSpectrum R` as its full stalk-rank
function.  The construction uses the idempotents of the clopen threshold sets
`{p | i < f p}`.  It also constructs the componentwise complementary module
and an explicit equivalence of their product with a finite standard free
module.

The supporting idempotent API computes the stalk rank of a principal ideal
generated by an idempotent and identifies the two complementary principal
ideals with the base ring.
-/

public section

open Function Set

universe u

namespace IsIdempotentElem

variable {R : Type u} [CommRing R] {e : R}

/-- Multiplication by `e`, regarded as a projection onto the principal ideal
generated by `e`. -/
noncomputable def spanProjection (e : R) :
    R →ₗ[R] Ideal.span {e} :=
  (LinearMap.toSpanSingleton R R e).codRestrict (Ideal.span {e}) fun r ↦ by
    rw [LinearMap.toSpanSingleton_apply, smul_eq_mul]
    exact Ideal.mem_span_singleton'.2 ⟨r, rfl⟩

/-- The idempotent-span projection retracts the inclusion into the base ring. -/
lemma spanProjection_comp_subtype (he : IsIdempotentElem e) :
    spanProjection e ∘ₗ (Ideal.span {e}).subtype = LinearMap.id := by
  ext x
  obtain ⟨r, hr⟩ := Ideal.mem_span_singleton'.1 x.property
  simp only [LinearMap.comp_apply, spanProjection, LinearMap.codRestrict_apply,
    LinearMap.toSpanSingleton_apply, smul_eq_mul, Submodule.coe_subtype, LinearMap.id_apply]
  rw [← hr, mul_assoc, he.eq]

/-- The principal ideal generated by an idempotent is projective. -/
theorem projective_span (he : IsIdempotentElem e) :
    Module.Projective R (Ideal.span {e}) :=
  Module.Projective.of_split (Ideal.span {e}).subtype (spanProjection e)
    he.spanProjection_comp_subtype

/-- The two ideals cut out by an idempotent are complementary. -/
noncomputable def spanProdEquiv (he : IsIdempotentElem e) :
    (Ideal.span {e} × Ideal.span {1 - e}) ≃ₗ[R] R where
  toFun x := x.1.1 + x.2.1
  invFun r := (spanProjection e r, spanProjection (1 - e) r)
  left_inv x := by
    have he0 : e * (1 - e) = 0 := by rw [mul_sub, mul_one, he.eq, sub_self]
    have h0e : (1 - e) * e = 0 := by rw [sub_mul, one_mul, he.eq, sub_self]
    apply Prod.ext <;> apply Subtype.ext
    · obtain ⟨r, hr⟩ := Ideal.mem_span_singleton'.1 x.1.property
      obtain ⟨s, hs⟩ := Ideal.mem_span_singleton'.1 x.2.property
      simp only [spanProjection, LinearMap.codRestrict_apply,
        LinearMap.toSpanSingleton_apply, smul_eq_mul]
      rw [add_mul, ← hr, ← hs, mul_assoc, he.eq]
      simp [mul_assoc, h0e]
    · obtain ⟨r, hr⟩ := Ideal.mem_span_singleton'.1 x.1.property
      obtain ⟨s, hs⟩ := Ideal.mem_span_singleton'.1 x.2.property
      simp only [spanProjection, LinearMap.codRestrict_apply,
        LinearMap.toSpanSingleton_apply, smul_eq_mul]
      rw [add_mul, ← hr, ← hs]
      simp [mul_assoc, he0, he.one_sub.eq]
  right_inv r := by
    simp [spanProjection, mul_sub]
  map_add' x y := by simp only [Prod.fst_add, Prod.snd_add, Submodule.coe_add]; abel
  map_smul' r x := by simp [mul_add]

/-- The ideal generated by an idempotent has stalk rank zero at a prime
containing the idempotent. -/
lemma rankAtStalk_span_eq_zero (he : IsIdempotentElem e)
    (p : PrimeSpectrum R) (hp : e ∈ p.asIdeal) :
    Module.rankAtStalk (R := R) (Ideal.span {e}) p = 0 := by
  let _ : Module.Finite R (Ideal.span {e}) := Module.Finite.span_singleton R e
  let _ : Module.Projective R (Ideal.span {e}) := he.projective_span
  apply (Module.rankAtStalk_eq_zero_iff_notMem_support p).2
  rw [Module.notMem_support_iff']
  intro m
  refine ⟨1 - e, ?_, ?_⟩
  · intro hcomp
    apply (Ideal.ne_top_iff_one p.asIdeal).mp (inferInstance : p.asIdeal.IsPrime).ne_top
    simpa using p.asIdeal.add_mem hp hcomp
  · apply Subtype.ext
    obtain ⟨r, hr⟩ := Ideal.mem_span_singleton'.1 m.property
    change (1 - e) * (m : R) = 0
    have h0e : (1 - e) * e = 0 := by rw [sub_mul, one_mul, he.eq, sub_self]
    calc
      (1 - e) * (m : R) = (1 - e) * (r * e) := by rw [hr]
      _ = r * ((1 - e) * e) := by ac_rfl
      _ = 0 := by rw [h0e, mul_zero]

/-- The ideal generated by an idempotent has stalk rank one at a prime not
containing the idempotent. -/
theorem rankAtStalk_span_eq_one (he : IsIdempotentElem e) (p : PrimeSpectrum R)
    (hp : e ∉ p.asIdeal) :
    Module.rankAtStalk (R := R) (Ideal.span {e}) p = 1 := by
  let _ : Module.Finite R (Ideal.span {e}) := Module.Finite.span_singleton R e
  let _ : Module.Projective R (Ideal.span {e}) := he.projective_span
  let _ : Module.Finite R (Ideal.span {1 - e}) := Module.Finite.span_singleton R (1 - e)
  let _ : Module.Projective R (Ideal.span {1 - e}) := he.one_sub.projective_span
  have he0 : e * (1 - e) = 0 := by rw [mul_sub, mul_one, he.eq, sub_self]
  have hcomp : 1 - e ∈ p.asIdeal :=
    ((inferInstance : p.asIdeal.IsPrime).mem_or_mem (he0 ▸ p.asIdeal.zero_mem)).resolve_left hp
  have hz := rankAtStalk_span_eq_zero he.one_sub p hcomp
  have hprod := congrFun
    (Module.rankAtStalk_prod (R := R) (Ideal.span {e}) (Ideal.span {1 - e})) p
  have hequiv := congrFun (Module.rankAtStalk_eq_of_equiv he.spanProdEquiv) p
  let _ : Nontrivial R := nontrivial_iff.mpr ⟨0, 1, fun h ↦ by
    apply (Ideal.ne_top_iff_one p.asIdeal).mp (inferInstance : p.asIdeal.IsPrime).ne_top
    rw [← h]
    exact p.asIdeal.zero_mem⟩
  calc
    Module.rankAtStalk (R := R) (Ideal.span {e}) p =
        Module.rankAtStalk (Ideal.span {e}) p + 0 := by simp
    _ = Module.rankAtStalk (Ideal.span {e}) p +
        Module.rankAtStalk (Ideal.span {1 - e}) p := by rw [hz]
    _ = Module.rankAtStalk (Ideal.span {e} × Ideal.span {1 - e}) p := hprod.symm
    _ = Module.rankAtStalk R p := hequiv
    _ = 1 := congrFun Module.rankAtStalk_self p

end IsIdempotentElem

namespace ModuleCat.FiniteProjective

variable {R : Type u} [CommRing R]

/-- A finite upper bound for a locally constant natural-valued function on a
prime spectrum. -/
noncomputable def rankBound (f : LocallyConstant (PrimeSpectrum R) ℕ) : ℕ :=
  f.range_finite.toFinset.sup id

/-- Every value of `f` is at most `rankBound f`. -/
lemma le_rankBound (f : LocallyConstant (PrimeSpectrum R) ℕ) (p : PrimeSpectrum R) :
    f p ≤ rankBound f := by
  unfold rankBound
  apply Finset.le_sup (f := id)
  exact f.range_finite.mem_toFinset.mpr (Set.mem_range_self p)

/-- The clopen threshold set on which the prescribed rank is greater than `i`. -/
def rankClopen (f : LocallyConstant (PrimeSpectrum R) ℕ)
    (i : Fin (rankBound f)) : TopologicalSpace.Clopens (PrimeSpectrum R) :=
  ⟨{p | i.1 < f p}, (isClopen_discrete _).preimage f.continuous⟩

/-- The idempotent cutting out the threshold set `rankClopen f i`. -/
noncomputable def rankIdempotent
    (f : LocallyConstant (PrimeSpectrum R) ℕ) (i : Fin (rankBound f)) : R :=
  (PrimeSpectrum.isIdempotentElemEquivClopens (R := R)).symm (rankClopen f i)

/-- A threshold idempotent is idempotent. -/
theorem rankIdempotent_isIdempotent
    (f : LocallyConstant (PrimeSpectrum R) ℕ) (i : Fin (rankBound f)) :
    IsIdempotentElem (rankIdempotent f i) :=
  ((PrimeSpectrum.isIdempotentElemEquivClopens (R := R)).symm (rankClopen f i)).2

/-- A threshold idempotent avoids precisely the primes where the rank is
strictly larger than its index. -/
theorem rankIdempotent_notMem_iff
    (f : LocallyConstant (PrimeSpectrum R) ℕ) (i : Fin (rankBound f))
    (p : PrimeSpectrum R) : rankIdempotent f i ∉ p.asIdeal ↔ i.1 < f p := by
  change p ∈ PrimeSpectrum.basicOpen (rankIdempotent f i) ↔ _
  unfold rankIdempotent
  rw [PrimeSpectrum.basicOpen_isIdempotentElemEquivClopens_symm (rankClopen f i)]
  rfl

/-- The explicit threshold-ideal module underlying
`ofLocallyConstantRank`. -/
abbrev rankModule (R : Type u) [CommRing R]
    (f : LocallyConstant (PrimeSpectrum R) ℕ) :=
  (i : Fin (rankBound f)) → Ideal.span {rankIdempotent f i}

private abbrev rankComplement (R : Type u) [CommRing R]
    (f : LocallyConstant (PrimeSpectrum R) ℕ) :=
  (i : Fin (rankBound f)) → Ideal.span {1 - rankIdempotent f i}

/-- The explicit threshold-ideal module is finitely generated. -/
theorem rankModuleFinite
    (f : LocallyConstant (PrimeSpectrum R) ℕ) : Module.Finite R (rankModule R f) := by
  let _ (i : Fin (rankBound f)) : Module.Finite R (Ideal.span {rankIdempotent f i}) :=
    Module.Finite.span_singleton R _
  exact Module.Finite.equiv
    (DirectSum.linearEquivFunOnFintype R (Fin (rankBound f))
      fun i ↦ Ideal.span {rankIdempotent f i})

/-- The explicit threshold-ideal module is projective. -/
theorem rankModuleProjective
    (f : LocallyConstant (PrimeSpectrum R) ℕ) : Module.Projective R (rankModule R f) := by
  let _ (i : Fin (rankBound f)) : Module.Projective R (Ideal.span {rankIdempotent f i}) :=
    (rankIdempotent_isIdempotent f i).projective_span
  exact Module.Projective.of_equiv'
    (DirectSum.linearEquivFunOnFintype R (Fin (rankBound f))
      fun i ↦ Ideal.span {rankIdempotent f i})

private lemma rankComplementFinite
    (f : LocallyConstant (PrimeSpectrum R) ℕ) : Module.Finite R (rankComplement R f) := by
  let _ (i : Fin (rankBound f)) : Module.Finite R (Ideal.span {1 - rankIdempotent f i}) :=
    Module.Finite.span_singleton R _
  exact Module.Finite.equiv
    (DirectSum.linearEquivFunOnFintype R (Fin (rankBound f))
      fun i ↦ Ideal.span {1 - rankIdempotent f i})

private lemma rankComplementProjective
    (f : LocallyConstant (PrimeSpectrum R) ℕ) : Module.Projective R (rankComplement R f) := by
  let _ (i : Fin (rankBound f)) : Module.Projective R
      (Ideal.span {1 - rankIdempotent f i}) :=
    (rankIdempotent_isIdempotent f i).one_sub.projective_span
  exact Module.Projective.of_equiv'
    (DirectSum.linearEquivFunOnFintype R (Fin (rankBound f))
      fun i ↦ Ideal.span {1 - rankIdempotent f i})

/-- A finite projective module realizing a locally constant stalk-rank function. -/
@[expose] noncomputable def ofLocallyConstantRank (R : Type u) [CommRing R]
    (f : LocallyConstant (PrimeSpectrum R) ℕ) : ModuleCat.FiniteProjective R := by
  let _ : Module.Finite R (rankModule R f) := rankModuleFinite f
  let _ : Module.Projective R (rankModule R f) := rankModuleProjective f
  exact ModuleCat.FiniteProjective.of R (rankModule R f)

/-- The complementary finite projective module in the finite-free realization
of a locally constant stalk-rank function. -/
noncomputable def complementOfLocallyConstantRank (R : Type u) [CommRing R]
    (f : LocallyConstant (PrimeSpectrum R) ℕ) : ModuleCat.FiniteProjective R := by
  let _ : Module.Finite R (rankComplement R f) := rankComplementFinite f
  let _ : Module.Projective R (rankComplement R f) := rankComplementProjective f
  exact ModuleCat.FiniteProjective.of R (rankComplement R f)

private def piProdEquiv (R : Type u) [CommRing R] {I : Type*}
    (A B : I → Type u) [∀ i, AddCommGroup (A i)] [∀ i, Module R (A i)]
    [∀ i, AddCommGroup (B i)] [∀ i, Module R (B i)] :
    ((∀ i, A i) × (∀ i, B i)) ≃ₗ[R] ∀ i, A i × B i where
  toFun x i := (x.1 i, x.2 i)
  invFun x := (fun i ↦ (x i).1, fun i ↦ (x i).2)
  left_inv _ := rfl
  right_inv _ := rfl
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

/-- The realizing module and its componentwise complement sum to a finite
standard free module. -/
noncomputable def prodComplementEquiv (R : Type u) [CommRing R]
    (f : LocallyConstant (PrimeSpectrum R) ℕ) :
    (ofLocallyConstantRank R f × complementOfLocallyConstantRank R f) ≃ₗ[R]
        (Fin (rankBound f) → R) := by
  change (rankModule R f × rankComplement R f) ≃ₗ[R] (Fin (rankBound f) → R)
  exact (piProdEquiv R
      (fun i : Fin (rankBound f) ↦ Ideal.span {rankIdempotent f i})
      (fun i : Fin (rankBound f) ↦ Ideal.span {1 - rankIdempotent f i})).trans
    (LinearEquiv.piCongrRight fun i ↦
      (rankIdempotent_isIdempotent f i).spanProdEquiv)

/-- The module constructed by `ofLocallyConstantRank` has the prescribed
stalk-rank function at every prime. -/
theorem rankAtStalk_ofLocallyConstantRank
    (f : LocallyConstant (PrimeSpectrum R) ℕ) :
    Module.rankAtStalk (R := R) (ofLocallyConstantRank R f) = f := by
  classical
  ext p
  change Module.rankAtStalk (rankModule R f) p = f p
  let _ (i : Fin (rankBound f)) : Module.Finite R (Ideal.span {rankIdempotent f i}) :=
    Module.Finite.span_singleton R _
  let _ (i : Fin (rankBound f)) : Module.Projective R (Ideal.span {rankIdempotent f i}) :=
    (rankIdempotent_isIdempotent f i).projective_span
  rw [Module.rankAtStalk_pi, finsum_eq_sum_of_fintype]
  calc
    (∑ i : Fin (rankBound f),
        Module.rankAtStalk (R := R) (Ideal.span {rankIdempotent f i}) p) =
        ∑ i : Fin (rankBound f), if i.1 < f p then 1 else 0 := by
      apply Finset.sum_congr rfl
      intro i _
      by_cases hi : i.1 < f p
      · rw [ite_eq_left hi]
        exact (rankIdempotent_isIdempotent f i).rankAtStalk_span_eq_one p
          ((rankIdempotent_notMem_iff f i p).2 hi)
      · rw [ite_eq_right hi]
        apply (rankIdempotent_isIdempotent f i).rankAtStalk_span_eq_zero p
        by_contra hmem
        exact hi ((rankIdempotent_notMem_iff f i p).1 hmem)
    _ = f p := by
      rw [← Finset.card_filter, Fin.card_filter_val_lt,
        Nat.min_eq_right (le_rankBound f p)]

end ModuleCat.FiniteProjective
