/-
SPDX-License-Identifier: Apache-2.0
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Formal Frontier Agents
-/
-- Contributors: Prism
module

public import ProjectiveModules.Module.RightExtension
public import Mathlib.Algebra.Module.Torsion.Basic
public import Mathlib.RingTheory.Congruence.Hom
public import Mathlib.RingTheory.TwoSidedIdeal.Operations

/-!
# Right-module extension along a quotient map

For a two-sided ideal `I` of a possibly noncommutative ring `R`, this file
identifies extension of scalars along `R → R ⧸ I` with quotienting a right
`R`-module by the right action of `I`.
-/

@[expose] public section

universe uR uM

open scoped Pointwise

namespace ModuleCat.RightExtension

variable {R : Type uR} [Ring R]

/-- A two-sided ideal of `R`, regarded as an ideal of the opposite ring. -/
abbrev oppositeIdeal (I : Ideal R) [I.IsTwoSided] : Ideal Rᵐᵒᵖ :=
  I.toTwoSided.op.asIdeal

/-- The canonical homomorphism from the opposite of a quotient ring to the
quotient of the opposite ring. -/
def quotientOppositeHom (I : Ideal R) [I.IsTwoSided] :
    (R ⧸ I)ᵐᵒᵖ →+* (Rᵐᵒᵖ ⧸ oppositeIdeal I) := by
  letI : (oppositeIdeal I).IsTwoSided := inferInstance
  let g₀ : R →+* (Rᵐᵒᵖ ⧸ oppositeIdeal I)ᵐᵒᵖ :=
    (RingHom.op (Ideal.Quotient.mk (oppositeIdeal I))).comp
      (RingEquiv.opOp R).toRingHom
  have hg₀ : ∀ x ∈ I, g₀ x = 0 := by
    intro x hx
    apply MulOpposite.unop_injective
    change Ideal.Quotient.mk (oppositeIdeal I) (MulOpposite.op x) = 0
    rw [Ideal.Quotient.eq_zero_iff_mem]
    change MulOpposite.op x ∈ I.toTwoSided.op.asIdeal
    rw [TwoSidedIdeal.mem_asIdeal, TwoSidedIdeal.mem_op_iff,
      Ideal.mem_toTwoSided]
    exact hx
  let g : R ⧸ I →+* (Rᵐᵒᵖ ⧸ oppositeIdeal I)ᵐᵒᵖ :=
    Ideal.Quotient.lift I g₀ hg₀
  exact ((RingEquiv.opOp (Rᵐᵒᵖ ⧸ oppositeIdeal I)).symm.toRingHom.comp
    (RingHom.op g))

@[simp]
theorem quotientOppositeHom_mk (I : Ideal R) [I.IsTwoSided] (r : R) :
    quotientOppositeHom I (MulOpposite.op (Ideal.Quotient.mk I r)) =
      Ideal.Quotient.mk (oppositeIdeal I) (MulOpposite.op r) := by
  rfl

theorem mem_oppositeIdeal_iff (I : Ideal R) [I.IsTwoSided] (r : R) :
    MulOpposite.op r ∈ oppositeIdeal I ↔ r ∈ I := by
  change MulOpposite.op r ∈ I.toTwoSided.op.asIdeal ↔ r ∈ I
  rw [TwoSidedIdeal.mem_asIdeal, TwoSidedIdeal.mem_op_iff,
    Ideal.mem_toTwoSided]
  simp

section IdealQuotient

variable {M : Type uM} [AddCommGroup M] [Module Rᵐᵒᵖ M]

/-- The submodule generated by the right action of a two-sided ideal. -/
abbrev idealSubmodule (I : Ideal R) [I.IsTwoSided] : Submodule Rᵐᵒᵖ M :=
  oppositeIdeal I • ⊤

/-- A right module modulo the right action of a two-sided ideal. -/
abbrev IdealQuotient (I : Ideal R) [I.IsTwoSided] :=
  M ⧸ idealSubmodule (M := M) I

@[instance_reducible]
instance idealQuotientModule (I : Ideal R) [I.IsTwoSided] :
    Module (R ⧸ I)ᵐᵒᵖ (IdealQuotient (M := M) I) := by
  letI : (oppositeIdeal I).IsTwoSided := inferInstance
  letI : Module (Rᵐᵒᵖ ⧸ oppositeIdeal I) (IdealQuotient (M := M) I) :=
    inferInstance
  exact Module.compHom _ (quotientOppositeHom I)

/-- The canonical semilinear map from a right module to its quotient by the
right action of a two-sided ideal. -/
def idealQuotientMk (I : Ideal R) [I.IsTwoSided] :
    M →ₛₗ[RingHom.op (Ideal.Quotient.mk I)] IdealQuotient (M := M) I := by
  letI : (oppositeIdeal I).IsTwoSided := inferInstance
  letI : Module (Rᵐᵒᵖ ⧸ oppositeIdeal I) (IdealQuotient (M := M) I) :=
    inferInstance
  exact
    { toFun := Submodule.Quotient.mk (p := idealSubmodule (M := M) I)
      map_add' := fun _ _ ↦ rfl
      map_smul' := fun r m ↦ by
        change quotientOppositeHom I
            (MulOpposite.op (Ideal.Quotient.mk I (MulOpposite.unop r))) •
              Submodule.Quotient.mk (p := idealSubmodule (M := M) I) m =
          Submodule.Quotient.mk (p := idealSubmodule (M := M) I) (r • m)
        rw [quotientOppositeHom_mk]
        exact Module.Quotient.mk_smul_mk M (oppositeIdeal I) r m }

@[simp]
theorem idealQuotientMk_apply (I : Ideal R) [I.IsTwoSided] (m : M) :
    idealQuotientMk (M := M) I m =
      Submodule.Quotient.mk (p := idealSubmodule (M := M) I) m := by
  rfl

/-- The quotient map induces a map from extension of scalars to the quotient
module. -/
def toIdealQuotient (I : Ideal R) [I.IsTwoSided] :
    Obj (Ideal.Quotient.mk I) M →ₗ[(R ⧸ I)ᵐᵒᵖ] IdealQuotient (M := M) I :=
  fromSemilinear (Ideal.Quotient.mk I) (idealQuotientMk (M := M) I)

@[simp]
theorem toIdealQuotient_tmul (I : Ideal R) [I.IsTwoSided] (m : M)
    (s : R ⧸ I) :
    toIdealQuotient (M := M) I (tmul (Ideal.Quotient.mk I) m s) =
      MulOpposite.op s •
        Submodule.Quotient.mk (p := idealSubmodule (M := M) I) m := by
  exact fromSemilinear_tmul _ _ _ _

theorem idealSubmodule_le_tmulOne_ker
    (I : Ideal R) [I.IsTwoSided] :
    idealSubmodule (M := M) I ≤
      (tmulOne (Ideal.Quotient.mk I : R →+* R ⧸ I) :
        M →ₛₗ[RingHom.op (Ideal.Quotient.mk I)]
          Obj (Ideal.Quotient.mk I) M).ker := by
  rw [idealSubmodule, Submodule.smul_le]
  intro r hr m _
  induction r using MulOpposite.rec' with
  | _ r =>
      change tmul (Ideal.Quotient.mk I) (MulOpposite.op r • m) 1 = 0
      rw [smul_tmul]
      have hr' : r ∈ I := (mem_oppositeIdeal_iff I r).mp hr
      rw [Ideal.Quotient.eq_zero_iff_mem.mpr hr']
      simp [tmul]

def fromIdealQuotientSemilinear (I : Ideal R) [I.IsTwoSided] :
    IdealQuotient (M := M) I →ₛₗ[RingHom.op (Ideal.Quotient.mk I)]
      Obj (Ideal.Quotient.mk I) M :=
  Submodule.liftQ (idealSubmodule (M := M) I)
    (tmulOne (Ideal.Quotient.mk I))
    (idealSubmodule_le_tmulOne_ker (M := M) I)

@[simp]
theorem fromIdealQuotientSemilinear_mk
    (I : Ideal R) [I.IsTwoSided] (m : M) :
    fromIdealQuotientSemilinear (M := M) I
        (Submodule.Quotient.mk (p := idealSubmodule (M := M) I) m) =
      tmul (Ideal.Quotient.mk I) m 1 := by
  exact Submodule.liftQ_apply _ _ _

/-- The map induced by `m ↦ m ⊗ 1` from the quotient module to extension of
scalars. -/
def fromIdealQuotient (I : Ideal R) [I.IsTwoSided] :
    IdealQuotient (M := M) I →ₗ[(R ⧸ I)ᵐᵒᵖ] Obj (Ideal.Quotient.mk I) M where
  toFun := fromIdealQuotientSemilinear (M := M) I
  map_add' := (fromIdealQuotientSemilinear (M := M) I).map_add
  map_smul' s x := by
    induction s using MulOpposite.rec' with
    | _ s =>
        obtain ⟨r, rfl⟩ := Ideal.Quotient.mk_surjective s
        induction x using Submodule.Quotient.induction_on with
        | _ m =>
            change fromIdealQuotientSemilinear (M := M) I
                ((MulOpposite.op (Ideal.Quotient.mk I r)) •
                  Submodule.Quotient.mk
                    (p := idealSubmodule (M := M) I) m) = _
            change fromIdealQuotientSemilinear (M := M) I
                (Submodule.Quotient.mk
                  (p := idealSubmodule (M := M) I)
                  (MulOpposite.op r • m)) = _
            rw [fromIdealQuotientSemilinear_mk,
              fromIdealQuotientSemilinear_mk]
            exact (tmulOne (Ideal.Quotient.mk I)).map_smulₛₗ
              (MulOpposite.op r) m

@[simp]
theorem fromIdealQuotient_mk (I : Ideal R) [I.IsTwoSided] (m : M) :
    fromIdealQuotient (M := M) I
        (Submodule.Quotient.mk (p := idealSubmodule (M := M) I) m) =
      tmul (Ideal.Quotient.mk I) m 1 := by
  exact fromIdealQuotientSemilinear_mk (M := M) I m

theorem fromIdealQuotient_comp_toIdealQuotient
    (I : Ideal R) [I.IsTwoSided] :
    (fromIdealQuotient (M := M) I).comp (toIdealQuotient (M := M) I) =
      LinearMap.id := by
  apply linearMap_ext
  intro m s
  rw [LinearMap.comp_apply, toIdealQuotient_tmul, map_smul,
    fromIdealQuotient_mk, tmul_smul]
  simp

theorem toIdealQuotient_comp_fromIdealQuotient
    (I : Ideal R) [I.IsTwoSided] :
    (toIdealQuotient (M := M) I).comp (fromIdealQuotient (M := M) I) =
      LinearMap.id := by
  apply LinearMap.ext
  intro x
  induction x using Submodule.Quotient.induction_on with
  | _ m =>
      rw [LinearMap.comp_apply, fromIdealQuotient_mk, toIdealQuotient_tmul]
      simp

/-- Extension of scalars along `R → R ⧸ I` is canonically the quotient by
the right action of `I`. -/
def idealQuotientLinearEquiv (I : Ideal R) [I.IsTwoSided] :
    Obj (Ideal.Quotient.mk I) M ≃ₗ[(R ⧸ I)ᵐᵒᵖ] IdealQuotient (M := M) I :=
  LinearEquiv.ofLinearMap (toIdealQuotient (M := M) I)
    (fromIdealQuotient (M := M) I)
    (toIdealQuotient_comp_fromIdealQuotient (M := M) I)
    (fromIdealQuotient_comp_toIdealQuotient (M := M) I)

@[simp]
theorem idealQuotientLinearEquiv_tmul (I : Ideal R) [I.IsTwoSided]
    (m : M) (s : R ⧸ I) :
    idealQuotientLinearEquiv (M := M) I
        (tmul (Ideal.Quotient.mk I) m s) =
      MulOpposite.op s •
        Submodule.Quotient.mk (p := idealSubmodule (M := M) I) m := by
  exact toIdealQuotient_tmul (M := M) I m s

@[simp]
theorem idealQuotientLinearEquiv_symm_mk
    (I : Ideal R) [I.IsTwoSided] (m : M) :
    (idealQuotientLinearEquiv (M := M) I).symm
        (Submodule.Quotient.mk (p := idealSubmodule (M := M) I) m) =
      tmul (Ideal.Quotient.mk I) m 1 := by
  exact fromIdealQuotient_mk (M := M) I m

/-- The kernel of the canonical map to extension along `R → R ⧸ I` is the
submodule generated by the right action of `I`. -/
theorem tmulOne_ker_quotient_mk (I : Ideal R) [I.IsTwoSided] :
    (tmulOne (Ideal.Quotient.mk I : R →+* R ⧸ I) :
        M →ₛₗ[RingHom.op (Ideal.Quotient.mk I)] Obj (Ideal.Quotient.mk I) M).ker =
      idealSubmodule (M := M) I := by
  apply le_antisymm
  · intro m hm
    rw [← Submodule.Quotient.mk_eq_zero]
    have h := idealQuotientLinearEquiv_tmul (M := M) I m (1 : R ⧸ I)
    simp only [MulOpposite.op_one, one_smul] at h
    rw [← h]
    rw [← tmulOne_apply, hm, map_zero]
  · exact idealSubmodule_le_tmulOne_ker (M := M) I

end IdealQuotient

end ModuleCat.RightExtension
